### ISSUE TITLE
"Incorrect Password" when using WiFi USB dongles with Roobi

### ISSUE THREAD

**Issue by MikeFarrington** [radxa-build/rock-5-itx#2]
Using various WiFi dongles, the correct WiFi password is never accepted.  I always receive the message
```
Error: Incorrect Password
```

This is using v1.2.0 that shipped with my Rock 5 ITX as well as with the latest v1.2.1.

**Comment by RadxaYuntian** [comment]
What v1.2.0 software you are referring to? Roobi?

**Comment by MikeFarrington** [comment]
Yes, sorry, I was talking about Roobi.  I noticed another Linux distro was giving the same issue, so this might not be specific to Roobi -- so I think it's safe to close this as not being a Roobi-specific or board-specific problem.  I was eventually able to connect via WiFi to a different access point.  I'll go ahead and close this.
